language: node_js
node_js:
- '10'
- '8'
- '6'
script: "npm run testTravis"
deploy:
  provider: npm
  email: info@entrecode.de
  api_key:
    secure: "Be81+6aZ/PZz+gHnoHAiD6r+dbwDZA0xIYS4KIOW1Z+Dl+cFbDiQKFzRgB66sLl6nN01NjvoPUTttgmkCe1tTp/j+gNuria0PyDo4R5eS4W2d8Xy4XJjVtZI/L0AyW3Mpg3pldHAYj1OSGbPSODEl0bkc6ku096XoFtFPJXLjwfPfPMdVagqmI5iB61o3RcfLRpvo0SRs8EkO03nhsiRFdxd0ktF0qNIB7XIhhGO2eplWg2zTY6fTGYEiHDcPI+AKX3R+XQ20U4XckGjZIFCtzDhLPaxaCQB3p8yYnNUNkhkLVcgkU3ZJa0kUg0Be7iiyxRxGmHgJ1ZJ3xySm5S3LRB3T+Opl4qg/VXmDfcMuMmeu6SkSd2NlnCriZPLOa8L6+fSk5zi7ZCwSLLBP6wwMAl2OEgeY0pfscDKWFyFR/sv+DbeCMy12kSe2gTZ1JC7KT80aNWDavCTD8c8ZQy8aiUEM1eCDAWEvrbLAjWwz7o2o/SjPKFHFikVlsjHxtPINbMmX2DQ6ZG5xKSzfQKfcGsqZvq0f4z/nMQrjMKPuU3LXJVAZDr679y5O8hYccqFZ1qqk6JWX1WQqwmRQfIjTVQotGOKKDPMlibAHUXZy8AUiqoIYBGtafruTSFj/lTCC+5YLQwKl3EzMuEG9CpyeGfzxPatf9ZHBxckirRJSLc="
  on:
    tags: true
    onBranch: master
  skip_cleanup: true
after_script: "npm run coveralls"
