language: node_js
node_js:
- '10'
- '8'
- '6'
script: npm run testTravis
deploy:
  provider: npm
  email: info@entrecode.de
  api_key:
    secure: PKCbI62pw8Ny32sxTsrhKTvffXAcEqcAbY+/Me0zrxZFZW0BD1T1u/diS0PP3+uzk9l0X4J7HFWaEfezH9cq47z3dwE9RlwTCwN8kFMYIbaAWrvDJQnIcRwmBng5M47xxwzydGgVsCdoz3PSVNZJlJL43Ku2vOCnRQdBY32E6Rl0YyOBVCaO6foK2Wl/WsfMDFC7C7iEI/fdJ68nQznagAgw+na1nqb5T6k6RFfNOL/ttKcDmCnsL116t4ASsMNH9L4mhBaWB/ZZP8vb2cF/nEr9igSdUmAJJnFIrt2kk00DIGhr2GVVK1Dm0VtH8Nw8ezZOwDke3g+H1WvmwYG0dQkfkmBb+XI7drnRRNyhAKJ7kQfoS75pbpu+cp1YWLN57aweMIVAr6+eNMxICIS7S6mm3YkNUm9C/ELZE/PpekBjm2M26VMIRylVBdc25y8FDcrQed+/pENI1J2pPOgNajRjwC8JnuSEfPHZLFxEyv913xqxJtn/ilqS1fSfVRp61eLJOlQjl6J0tO2aAJTWNP4U0zjg410gr4bnH83IcfQC+Nl/MyUTcboknG7qHFgoEqf3l40lTI84GfRPtH5nQCmk+6XeC1w9nemgsO1CP9rTwiYCsOoVP0bAz6WnT2dMixZRut2gIpYlF3EgfA2B+Rv0cDK1BuoUR7/yCjom5SA=
  on:
    tags: true
    onBranch: master
  skip_cleanup: true
after_script: npm run coveralls
